apiVersion: v1
kind: Service
metadata:
  name: discovery
  namespace: spring-apps
spec:
  type: NodePort
  selector:
    app: discovery
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000